import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yash Sikarwar — Full Stack Developer",
  description: "Portfolio of Yash Sikarwar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ overflowX: "hidden" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-zinc-950 text-zinc-100 antialiased`}
        style={{ overflowX: "hidden", maxWidth: "100vw" }}
      >
        <Sidebar />
        <div className="pt-15 md:pt-8 pb-15 md:pb-0 w-full overflow-x-hidden">
          <main className="min-h-screen w-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Sidebar from "./components/sidebar";
// import Footer from "./components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.className} ${geistMono.className} bg-zinc-950 text-zinc-100 antialiased`}
//       >
//         <div className="min-h-screen flex">
//           <Sidebar />
//           <div className="flex-1 md:ml-65 ml-10px">
//             <main className="min-h-screen">{children}</main>
//             <Footer />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
